{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nexus-saas.fullname" . }}-backend
  labels:
    {{- include "nexus-saas.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "nexus-saas.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nexus-saas.fullname" . }}-frontend
  labels:
    {{- include "nexus-saas.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "nexus-saas.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
