apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nexus-saas.fullname" . }}-media
  labels:
    {{- include "nexus-saas.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd
