apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-saas.fullname" . }}-db
  labels:
    {{- include "nexus-saas.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "nexus-saas.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-saas.fullname" . }}-redis
  labels:
    {{- include "nexus-saas.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: "redis://:{{ .Values.redis.auth.password }}@{{ include "nexus-saas.fullname" . }}-redis-master:6379/0"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-saas.fullname" . }}-secrets
  labels:
    {{- include "nexus-saas.labels" . | nindent 4 }}
type: Opaque
stringData:
  django-secret-key: {{ randAlphaNum 50 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-saas.fullname" . }}-stripe
  labels:
    {{- include "nexus-saas.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ .Values.stripe.secretKey | default "" | quote }}
  webhook-secret: {{ .Values.stripe.webhookSecret | default "" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-saas.fullname" . }}-sentry
  labels:
    {{- include "nexus-saas.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ .Values.sentry.dsn | default "" | quote }}
