# Generated by Django 4.2.30 on 2026-07-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_code', models.CharField(max_length=100, unique=True)),
                ('asset_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Movable', 'Movable'), ('IT Equipment', 'IT Equipment'), ('Vehicle', 'Vehicle'), ('Furniture', 'Furniture'), ('Machinery', 'Machinery')], default='Fixed', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('depreciation_method', models.CharField(choices=[('Straight Line', 'Straight Line'), ('Declining Balance', 'Declining Balance'), ('None', 'None')], default='Straight Line', max_length=50)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual depreciation rate as a percentage', max_digits=5)),
                ('useful_life_years', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('In Maintenance', 'In Maintenance'), ('Disposed', 'Disposed')], default='Draft', max_length=50)),
                ('condition', models.CharField(blank=True, choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=50)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('maintenance_schedule', models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual'), ('None', 'None')], max_length=100)),
                ('insurance_policy', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='asset_images/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
