from django.core.management.base import BaseCommand
from apps.industries.models import IndustryCatalog, IndustryControl, AIAgentRegistry

class Command(BaseCommand):
    help = 'Seed the Industry Control Library with 100+ industries'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('Seeding Industry Control Library...'))

        industries = [
            {"industry_id": "AVI", "name": "Aviation & Airlines", "name_ar": "الطيران والخطوط الجوية", "category": "Transportation", "description": "Airlines, aircraft operations, aviation services", "icon": "Plane", "color": "#3b82f6", "is_active": True, "is_premium": True, "required_license_tier": "industry", "sort_order": 1},
            {"industry_id": "AIRPORT", "name": "Airport Management", "name_ar": "إدارة المطارات", "category": "Transportation", "description": "Airport operations and facilities", "icon": "Plane", "color": "#06b6d4", "is_active": True, "is_premium": True, "required_license_tier": "industry", "sort_order": 2},
            {"industry_id": "HLT", "name": "Hospital & Healthcare", "name_ar": "المستشفيات والرعاية الصحية", "category": "Healthcare", "description": "Hospitals and medical systems", "icon": "Heart", "color": "#ef4444", "is_active": True, "is_premium": True, "required_license_tier": "industry", "sort_order": 3},
            {"industry_id": "CLN", "name": "Clinics & Medical Centers", "name_ar": "العيادات والمراكز الطبية", "category": "Healthcare", "description": "Outpatient healthcare", "icon": "Stethoscope", "color": "#f97316", "is_active": True, "is_premium": False, "required_license_tier": "business", "sort_order": 4},
            {"industry_id": "PHA", "name": "Pharmaceutical", "name_ar": "الأدوية والصيدلة", "category": "Healthcare", "description": "Drug manufacturing and distribution", "icon": "Pill", "color": "#8b5cf6", "is_active": True, "is_premium": True, "required_license_tier": "industry", "sort_order": 5},
            {"industry_id": "MFG", "name": "Manufacturing", "name_ar": "التصنيع", "category": "Industrial", "description": "General manufacturing", "icon": "Factory", "color": "#64748b", "is_active": True, "is_premium": False, "required_license_tier": "business", "sort_order": 6},
            {"industry_id": "AUTO", "name": "Automotive Manufacturing", "name_ar": "تصنيع السيارات", "category": "Industrial", "description": "Vehicle production", "icon": "Car", "color": "#1e293b", "is_active": True, "is_premium": True, "required_license_tier": "industry", "sort_order": 7},
            {"industry_id": "FNB", "name": "Food & Beverage", "name_ar": "الأغذية والمشروبات", "category": "Manufacturing", "description": "Food production", "icon": "Utensils", "color": "#22c55e", "is_active": True, "is_premium": False, "required_license_tier": "business", "sort_order": 8},
            {"industry_id": "CON", "name": "Construction", "name_ar": "البناء والإنشاءات", "category": "Engineering", "description": "Construction projects", "icon": "HardHat", "color": "#f59e0b", "is_active": True, "is_premium": False, "required_license_tier": "business", "sort_order": 9},
            {"industry_id": "ENG", "name": "Engineering Services", "name_ar": "خدمات الهندسة", "category": "Engineering", "description": "Engineering companies", "icon": "Wrench", "color": "#6366f1", "is_active": True, "is_premium": False, "required_license_tier": "business", "sort_order": 10},
            {"industry_id": "OIL", "name": "Oil & Gas", "name_ar": "النفط والغاز", "category": "Energy", "description": "Oil and gas operations", "icon": "Fuel", "color": "#78350f", "is_active": True, "is_premium": True, "required_license_tier": "enterprise", "sort_order": 11},
            {"industry_id": "ENE", "name": "Energy & Utilities", "name_ar": "الطاقة والمرافق", "category": "Energy", "description": "Power and utilities", "icon": "Zap", "color": "#eab308", "is_active": True, "is_premium": True, "required_license_tier": "industry", "sort_order": 12},
            {"industry_id": "REN", "name": "Renewable Energy", "name_ar": "الطاقة المتجددة", "category": "Energy", "description": "Solar and wind energy", "icon": "Sun", "color": "#fbbf24", "is_active": True, "is_premium": True, "required_license_tier": "industry", "sort_order": 13},
            {"industry_id": "MIN", "name": "Mining", "name_ar": "التعدين", "category": "Industrial", "description": "Mining operations", "icon": "Pickaxe", "color": "#57534e", "is_active": True, "is_premium": True, "required_license_tier": "enterprise", "sort_order": 14},
            {"industry_id": "BANK", "name": "Banking", "name_ar": "الخدمات المصرفية", "category": "Finance", "description": "Banking operations", "icon": "Landmark", "color": "#0f766e", "is_active": True, "is_premium": True, "required_license_tier": "enterprise", "sort_order": 15},
            {"industry_id": "INS", "name": "Insurance", "name_ar": "التأمين", "category": "Finance", "description": "Insurance services", "icon": "Shield", "color": "#0e7490", "is_active": True, "is_premium": True, "required_license_tier": "industry", "sort_order": 16},
            {"industry_id": "RET", "name": "Retail", "name_ar": "التجزئة", "category": "Commerce", "description": "Retail operations", "icon": "ShoppingBag", "color": "#db2777", "is_active": True, "is_premium": False, "required_license_tier": "business", "sort_order": 17},
            {"industry_id": "ECOM", "name": "E-Commerce", "name_ar": "التجارة الإلكترونية", "category": "Commerce", "description": "Online commerce", "icon": "Globe", "color": "#7c3aed", "is_active": True, "is_premium": False, "required_license_tier": "business", "sort_order": 18},
            {"industry_id": "LOG", "name": "Logistics", "name_ar": "الخدمات اللوجستية", "category": "Transportation", "description": "Logistics and supply chain", "icon": "Truck", "color": "#4338ca", "is_active": True, "is_premium": False, "required_license_tier": "business", "sort_order": 19},
            {"industry_id": "GOV", "name": "Government", "name_ar": "الحكومة", "category": "Public Sector", "description": "Government operations", "icon": "Landmark", "color": "#1e3a5f", "is_active": True, "is_premium": True, "required_license_tier": "enterprise", "sort_order": 20},
        ]

        # Add 80 expansion slots
        for i in range(21, 101):
            industries.append({
                "industry_id": f"IND{i:03d}",
                "name": f"Industry Sector {i}",
                "name_ar": f"قطاع صناعي {i}",
                "category": "General",
                "description": "Sector expansion library",
                "icon": "Building2",
                "color": "#94a3b8",
                "is_active": False,
                "is_premium": False,
                "required_license_tier": "starter",
                "sort_order": i
            })

        created_count = 0
        for ind_data in industries:
            obj, created = IndustryCatalog.objects.update_or_create(
                industry_id=ind_data["industry_id"],
                defaults=ind_data
            )
            if created:
                created_count += 1

        self.stdout.write(self.style.SUCCESS(f'Created {created_count} industries, updated {len(industries) - created_count}'))

        # Seed controls for active industries
        self.seed_controls()
        self.seed_ai_agents()

        self.stdout.write(self.style.SUCCESS('Industry Control Library seeding complete!'))

    def seed_controls(self):
        self.stdout.write('Seeding industry controls...')

        controls_data = [
            # Aviation
            {"industry_id": "AVI", "control_id": "AVI-FOP-001", "module": "Flight Operations", "control_name": "Flight Planning", "sub_control": "Route Planning", "description": "Plan and optimize flight routes for safety and efficiency", "control_type": "operational", "is_required": True, "severity": "critical", "ai_agent_name": "Flight AI Agent", "database_entity": "Flight", "kpi_name": "On Time Performance", "kpi_formula": "(on_time_flights / total_flights) * 100", "kpi_target": 95, "kpi_unit": "%", "compliance_framework": "IATA", "compliance_standard": "IATA OPS", "regulatory_reference": "IATA Resolution 753"},
            {"industry_id": "AVI", "control_id": "AVI-MNT-001", "module": "Maintenance", "control_name": "Work Orders", "sub_control": "Maintenance Tasks", "description": "Aircraft maintenance management and tracking", "control_type": "operational", "is_required": True, "severity": "critical", "ai_agent_name": "Maintenance AI Agent", "database_entity": "MaintenanceOrder", "kpi_name": "Aircraft Downtime", "kpi_formula": "total_downtime_hours", "kpi_target": 24, "kpi_unit": "hours", "compliance_framework": "FAA", "compliance_standard": "FAR Part 145", "regulatory_reference": "14 CFR 145"},
            {"industry_id": "AVI", "control_id": "AVI-SAF-001", "module": "Safety", "control_name": "Safety Management System", "sub_control": "Incident Reporting", "description": "Safety incident tracking and analysis", "control_type": "safety", "is_required": True, "severity": "critical", "ai_agent_name": "Safety AI Agent", "database_entity": "SafetyIncident", "kpi_name": "Safety Incident Rate", "kpi_formula": "(incidents / flights) * 1000000", "kpi_target": 0, "kpi_unit": "per million", "compliance_framework": "ICAO", "compliance_standard": "SMS", "regulatory_reference": "ICAO Annex 19"},
            {"industry_id": "AVI", "control_id": "AVI-CRG-001", "module": "Cargo", "control_name": "Cargo Handling", "sub_control": "Dangerous Goods", "description": "Dangerous goods handling and compliance", "control_type": "compliance", "is_required": True, "severity": "high", "ai_agent_name": "Cargo AI Agent", "database_entity": "CargoShipment", "kpi_name": "Cargo Compliance Rate", "kpi_formula": "(compliant_shipments / total_shipments) * 100", "kpi_target": 100, "kpi_unit": "%", "compliance_framework": "IATA", "compliance_standard": "DGR", "regulatory_reference": "IATA DGR 2024"},

            # Healthcare
            {"industry_id": "HLT", "control_id": "HLT-PAT-001", "module": "Patient Management", "control_name": "Patient Registration", "sub_control": "Patient Profile", "description": "Manage patient records and registration", "control_type": "operational", "is_required": True, "severity": "critical", "ai_agent_name": "Patient AI Agent", "database_entity": "Patient", "kpi_name": "Patient Satisfaction", "kpi_formula": "avg(satisfaction_score)", "kpi_target": 90, "kpi_unit": "%", "compliance_framework": "HIPAA", "compliance_standard": "HIPAA Privacy", "regulatory_reference": "45 CFR 160"},
            {"industry_id": "HLT", "control_id": "HLT-CLN-001", "module": "Clinical", "control_name": "Medical Records", "sub_control": "Diagnosis", "description": "Clinical documentation and records management", "control_type": "compliance", "is_required": True, "severity": "critical", "ai_agent_name": "Clinical AI Agent", "database_entity": "MedicalRecord", "kpi_name": "Treatment Quality", "kpi_formula": "(successful_treatments / total_treatments) * 100", "kpi_target": 95, "kpi_unit": "%", "compliance_framework": "JCI", "compliance_standard": "JCI Standards", "regulatory_reference": "JCI 6th Edition"},
            {"industry_id": "HLT", "control_id": "HLT-PHR-001", "module": "Pharmacy", "control_name": "Medication Management", "sub_control": "Prescription Verification", "description": "Medication dispensing and verification", "control_type": "safety", "is_required": True, "severity": "critical", "ai_agent_name": "Pharmacy AI Agent", "database_entity": "Prescription", "kpi_name": "Medication Error Rate", "kpi_formula": "(errors / total_prescriptions) * 100", "kpi_target": 0.1, "kpi_unit": "%", "compliance_framework": "SFDA", "compliance_standard": "GMP", "regulatory_reference": "SFDA Guidelines"},
            {"industry_id": "HLT", "control_id": "HLT-LAB-001", "module": "Laboratory", "control_name": "Lab Quality Control", "sub_control": "Test Accuracy", "description": "Laboratory test quality and accuracy", "control_type": "quality", "is_required": True, "severity": "high", "ai_agent_name": "Lab AI Agent", "database_entity": "LabTest", "kpi_name": "Lab Accuracy", "kpi_formula": "(accurate_tests / total_tests) * 100", "kpi_target": 99, "kpi_unit": "%", "compliance_framework": "ISO", "compliance_standard": "ISO 15189", "regulatory_reference": "ISO 15189:2022"},

            # Manufacturing
            {"industry_id": "MFG", "control_id": "MFG-PRO-001", "module": "Production", "control_name": "Production Planning", "sub_control": "MRP", "description": "Production planning and material requirements", "control_type": "operational", "is_required": True, "severity": "high", "ai_agent_name": "Production AI Agent", "database_entity": "ProductionOrder", "kpi_name": "OEE", "kpi_formula": "availability * performance * quality", "kpi_target": 85, "kpi_unit": "%", "compliance_framework": "ISO", "compliance_standard": "ISO 9001", "regulatory_reference": "ISO 9001:2015"},
            {"industry_id": "MFG", "control_id": "MFG-QA-001", "module": "Quality", "control_name": "Quality Inspection", "sub_control": "Defect Tracking", "description": "Quality control process and defect tracking", "control_type": "quality", "is_required": True, "severity": "high", "ai_agent_name": "Quality AI Agent", "database_entity": "Inspection", "kpi_name": "Defect Rate", "kpi_formula": "(defects / total_produced) * 100", "kpi_target": 1, "kpi_unit": "%", "compliance_framework": "ISO", "compliance_standard": "ISO 9001", "regulatory_reference": "ISO 9001:2015"},
            {"industry_id": "MFG", "control_id": "MFG-ENV-001", "module": "Environmental", "control_name": "Environmental Management", "sub_control": "Emissions Control", "description": "Environmental impact monitoring and control", "control_type": "environmental", "is_required": False, "severity": "medium", "ai_agent_name": "Environmental AI Agent", "database_entity": "EmissionRecord", "kpi_name": "Carbon Footprint", "kpi_formula": "total_co2_emissions", "kpi_target": 1000, "kpi_unit": "tons", "compliance_framework": "ISO", "compliance_standard": "ISO 14001", "regulatory_reference": "ISO 14001:2015"},

            # Banking
            {"industry_id": "BANK", "control_id": "BANK-KYC-001", "module": "KYC", "control_name": "Know Your Customer", "sub_control": "Customer Verification", "description": "Customer identity verification and due diligence", "control_type": "compliance", "is_required": True, "severity": "critical", "ai_agent_name": "KYC AI Agent", "database_entity": "CustomerVerification", "kpi_name": "KYC Completion Rate", "kpi_formula": "(verified_customers / total_customers) * 100", "kpi_target": 100, "kpi_unit": "%", "compliance_framework": "Basel", "compliance_standard": "Basel III", "regulatory_reference": "Basel III KYC"},
            {"industry_id": "BANK", "control_id": "BANK-AML-001", "module": "AML", "control_name": "Anti-Money Laundering", "sub_control": "Transaction Monitoring", "description": "Monitor transactions for suspicious activity", "control_type": "compliance", "is_required": True, "severity": "critical", "ai_agent_name": "AML AI Agent", "database_entity": "TransactionAlert", "kpi_name": "False Positive Rate", "kpi_formula": "(false_positives / total_alerts) * 100", "kpi_target": 5, "kpi_unit": "%", "compliance_framework": "FATF", "compliance_standard": "FATF 40", "regulatory_reference": "FATF Recommendation 20"},
            {"industry_id": "BANK", "control_id": "BANK-CRD-001", "module": "Credit", "control_name": "Credit Risk Assessment", "sub_control": "Loan Scoring", "description": "Credit risk evaluation and scoring", "control_type": "financial", "is_required": True, "severity": "high", "ai_agent_name": "Credit AI Agent", "database_entity": "CreditApplication", "kpi_name": "NPL Ratio", "kpi_formula": "(non_performing_loans / total_loans) * 100", "kpi_target": 3, "kpi_unit": "%", "compliance_framework": "Basel", "compliance_standard": "Basel III", "regulatory_reference": "Basel III Credit Risk"},
            {"industry_id": "BANK", "control_id": "BANK-FRD-001", "module": "Fraud", "control_name": "Fraud Detection", "sub_control": "Real-time Monitoring", "description": "Real-time fraud detection and prevention", "control_type": "security", "is_required": True, "severity": "critical", "ai_agent_name": "Fraud AI Agent", "database_entity": "FraudAlert", "kpi_name": "Fraud Detection Rate", "kpi_formula": "(detected_frauds / total_frauds) * 100", "kpi_target": 99, "kpi_unit": "%", "compliance_framework": "PCI", "compliance_standard": "PCI DSS", "regulatory_reference": "PCI DSS v4.0"},

            # Oil & Gas
            {"industry_id": "OIL", "control_id": "OIL-HSE-001", "module": "HSE", "control_name": "Health Safety Environment", "sub_control": "Incident Prevention", "description": "HSE incident prevention and management", "control_type": "safety", "is_required": True, "severity": "critical", "ai_agent_name": "HSE AI Agent", "database_entity": "HSEIncident", "kpi_name": "TRIR", "kpi_formula": "(incidents * 200000) / total_hours", "kpi_target": 1, "kpi_unit": "per 200k hrs", "compliance_framework": "API", "compliance_standard": "API RP 754", "regulatory_reference": "API RP 754"},
            {"industry_id": "OIL", "control_id": "OIL-EMI-001", "module": "Emissions", "control_name": "Emissions Monitoring", "sub_control": "GHG Tracking", "description": "Greenhouse gas emissions monitoring", "control_type": "environmental", "is_required": True, "severity": "high", "ai_agent_name": "Emissions AI Agent", "database_entity": "EmissionReading", "kpi_name": "Methane Intensity", "kpi_formula": "(methane_emissions / gas_production) * 100", "kpi_target": 0.2, "kpi_unit": "%", "compliance_framework": "EPA", "compliance_standard": "EPA 40 CFR", "regulatory_reference": "EPA 40 CFR Part 60"},

            # Retail
            {"industry_id": "RET", "control_id": "RET-POS-001", "module": "POS", "control_name": "Point of Sale", "sub_control": "Transaction Processing", "description": "POS transaction processing and reconciliation", "control_type": "operational", "is_required": True, "severity": "medium", "ai_agent_name": "POS AI Agent", "database_entity": "POSTransaction", "kpi_name": "Transaction Accuracy", "kpi_formula": "(accurate_transactions / total_transactions) * 100", "kpi_target": 99.9, "kpi_unit": "%", "compliance_framework": "PCI", "compliance_standard": "PCI DSS", "regulatory_reference": "PCI DSS v4.0"},
            {"industry_id": "RET", "control_id": "RET-INV-001", "module": "Inventory", "control_name": "Inventory Management", "sub_control": "Stock Optimization", "description": "Inventory optimization and stock management", "control_type": "operational", "is_required": True, "severity": "medium", "ai_agent_name": "Inventory AI Agent", "database_entity": "InventoryItem", "kpi_name": "Stock Turnover", "kpi_formula": "cogs / avg_inventory", "kpi_target": 12, "kpi_unit": "times", "compliance_framework": "ISO", "compliance_standard": "ISO 28000", "regulatory_reference": "ISO 28000:2022"},

            # E-Commerce
            {"industry_id": "ECOM", "control_id": "ECOM-ORD-001", "module": "Orders", "control_name": "Order Processing", "sub_control": "Fulfillment", "description": "Order processing and fulfillment tracking", "control_type": "operational", "is_required": True, "severity": "medium", "ai_agent_name": "Order AI Agent", "database_entity": "Order", "kpi_name": "Order Fulfillment Rate", "kpi_formula": "(fulfilled_orders / total_orders) * 100", "kpi_target": 98, "kpi_unit": "%", "compliance_framework": "PCI", "compliance_standard": "PCI DSS", "regulatory_reference": "PCI DSS v4.0"},
            {"industry_id": "ECOM", "control_id": "ECOM-SEO-001", "module": "SEO", "control_name": "Search Optimization", "sub_control": "Ranking", "description": "SEO performance and ranking optimization", "control_type": "operational", "is_required": False, "severity": "low", "ai_agent_name": "SEO AI Agent", "database_entity": "SEOMetric", "kpi_name": "Organic Traffic", "kpi_formula": "total_organic_visits", "kpi_target": 100000, "kpi_unit": "visits", "compliance_framework": "GDPR", "compliance_standard": "GDPR", "regulatory_reference": "GDPR Article 6"},

            # Construction
            {"industry_id": "CON", "control_id": "CON-PRJ-001", "module": "Project Control", "control_name": "Project Management", "sub_control": "Schedule Control", "description": "Construction project scheduling and control", "control_type": "operational", "is_required": True, "severity": "high", "ai_agent_name": "Project AI Agent", "database_entity": "ConstructionProject", "kpi_name": "Schedule Performance", "kpi_formula": "(earned_value / planned_value) * 100", "kpi_target": 95, "kpi_unit": "%", "compliance_framework": "ISO", "compliance_standard": "ISO 9001", "regulatory_reference": "ISO 9001:2015"},
            {"industry_id": "CON", "control_id": "CON-SAF-001", "module": "Safety", "control_name": "Construction Safety", "sub_control": "Site Safety", "description": "Construction site safety management", "control_type": "safety", "is_required": True, "severity": "critical", "ai_agent_name": "Safety AI Agent", "database_entity": "SafetyIncident", "kpi_name": "LTIFR", "kpi_formula": "(lost_time_injuries * 1000000) / total_hours", "kpi_target": 2, "kpi_unit": "per million", "compliance_framework": "OSHA", "compliance_standard": "OSHA 1926", "regulatory_reference": "29 CFR 1926"},

            # Food & Beverage
            {"industry_id": "FNB", "control_id": "FNB-HAC-001", "module": "HACCP", "control_name": "HACCP Plan", "sub_control": "Critical Control Points", "description": "HACCP critical control points monitoring", "control_type": "safety", "is_required": True, "severity": "critical", "ai_agent_name": "Food Safety AI Agent", "database_entity": "HACCPRecord", "kpi_name": "HACCP Compliance", "kpi_formula": "(compliant_ccps / total_ccps) * 100", "kpi_target": 100, "kpi_unit": "%", "compliance_framework": "HACCP", "compliance_standard": "Codex Alimentarius", "regulatory_reference": "Codex Alimentarius HACCP"},
            {"industry_id": "FNB", "control_id": "FNB-LOT-001", "module": "Lot Tracking", "control_name": "Lot Traceability", "sub_control": "Batch Tracking", "description": "Product lot tracking and traceability", "control_type": "quality", "is_required": True, "severity": "high", "ai_agent_name": "Traceability AI Agent", "database_entity": "LotRecord", "kpi_name": "Traceability Rate", "kpi_formula": "(traceable_products / total_products) * 100", "kpi_target": 100, "kpi_unit": "%", "compliance_framework": "ISO", "compliance_standard": "ISO 22000", "regulatory_reference": "ISO 22000:2018"},

            # Energy
            {"industry_id": "ENE", "control_id": "ENE-GRD-001", "module": "Grid", "control_name": "Grid Management", "sub_control": "Load Balancing", "description": "Power grid load balancing and management", "control_type": "operational", "is_required": True, "severity": "critical", "ai_agent_name": "Grid AI Agent", "database_entity": "GridNode", "kpi_name": "Grid Stability", "kpi_formula": "(stable_hours / total_hours) * 100", "kpi_target": 99.99, "kpi_unit": "%", "compliance_framework": "NERC", "compliance_standard": "NERC CIP", "regulatory_reference": "NERC CIP-002"},
            {"industry_id": "ENE", "control_id": "ENE-SMT-001", "module": "Smart Meter", "control_name": "Smart Metering", "sub_control": "Consumption Tracking", "description": "Smart meter consumption tracking and billing", "control_type": "operational", "is_required": True, "severity": "medium", "ai_agent_name": "Meter AI Agent", "database_entity": "MeterReading", "kpi_name": "Meter Accuracy", "kpi_formula": "(accurate_readings / total_readings) * 100", "kpi_target": 99.5, "kpi_unit": "%", "compliance_framework": "IEC", "compliance_standard": "IEC 62056", "regulatory_reference": "IEC 62056-21"},

            # Renewable Energy
            {"industry_id": "REN", "control_id": "REN-SOL-001", "module": "Solar", "control_name": "Solar Panel Efficiency", "sub_control": "Performance Monitoring", "description": "Solar panel performance and efficiency monitoring", "control_type": "operational", "is_required": True, "severity": "medium", "ai_agent_name": "Solar AI Agent", "database_entity": "SolarPanel", "kpi_name": "Capacity Factor", "kpi_formula": "(actual_output / max_output) * 100", "kpi_target": 25, "kpi_unit": "%", "compliance_framework": "IEC", "compliance_standard": "IEC 61215", "regulatory_reference": "IEC 61215:2021"},
            {"industry_id": "REN", "control_id": "REN-WND-001", "module": "Wind", "control_name": "Wind Turbine Performance", "sub_control": "Power Output", "description": "Wind turbine performance optimization", "control_type": "operational", "is_required": True, "severity": "medium", "ai_agent_name": "Wind AI Agent", "database_entity": "WindTurbine", "kpi_name": "Availability", "kpi_formula": "(available_hours / total_hours) * 100", "kpi_target": 97, "kpi_unit": "%", "compliance_framework": "IEC", "compliance_standard": "IEC 61400", "regulatory_reference": "IEC 61400-1"},

            # Insurance
            {"industry_id": "INS", "control_id": "INS-UND-001", "module": "Underwriting", "control_name": "Risk Assessment", "sub_control": "Policy Scoring", "description": "Insurance risk assessment and policy scoring", "control_type": "financial", "is_required": True, "severity": "high", "ai_agent_name": "Underwriting AI Agent", "database_entity": "PolicyApplication", "kpi_name": "Loss Ratio", "kpi_formula": "(claims_paid / premiums_earned) * 100", "kpi_target": 70, "kpi_unit": "%", "compliance_framework": "Solvency", "compliance_standard": "Solvency II", "regulatory_reference": "Solvency II Directive"},
            {"industry_id": "INS", "control_id": "INS-CLM-001", "module": "Claims", "control_name": "Claims Processing", "sub_control": "Fraud Detection", "description": "Claims processing and fraud detection", "control_type": "operational", "is_required": True, "severity": "high", "ai_agent_name": "Claims AI Agent", "database_entity": "Claim", "kpi_name": "Claims Settlement Speed", "kpi_formula": "avg(settlement_days)", "kpi_target": 14, "kpi_unit": "days", "compliance_framework": "IFRS", "compliance_standard": "IFRS 17", "regulatory_reference": "IFRS 17"},

            # Government
            {"industry_id": "GOV", "control_id": "GOV-BUD-001", "module": "Budget", "control_name": "Budget Management", "sub_control": "Expenditure Control", "description": "Government budget management and control", "control_type": "financial", "is_required": True, "severity": "high", "ai_agent_name": "Budget AI Agent", "database_entity": "BudgetLine", "kpi_name": "Budget Variance", "kpi_formula": "((actual - budget) / budget) * 100", "kpi_target": 5, "kpi_unit": "%", "compliance_framework": "ISO", "compliance_standard": "ISO 27001", "regulatory_reference": "ISO 27001:2022"},
            {"industry_id": "GOV", "control_id": "GOV-SEC-001", "module": "Security", "control_name": "Information Security", "sub_control": "Access Control", "description": "Government information security management", "control_type": "security", "is_required": True, "severity": "critical", "ai_agent_name": "Security AI Agent", "database_entity": "SecurityIncident", "kpi_name": "Security Incident Rate", "kpi_formula": "(incidents / total_systems) * 100", "kpi_target": 0, "kpi_unit": "%", "compliance_framework": "ISO", "compliance_standard": "ISO 27001", "regulatory_reference": "ISO 27001:2022"},

            # Logistics
            {"industry_id": "LOG", "control_id": "LOG-TRK-001", "module": "Tracking", "control_name": "Shipment Tracking", "sub_control": "Real-time Location", "description": "Real-time shipment tracking and monitoring", "control_type": "operational", "is_required": True, "severity": "medium", "ai_agent_name": "Tracking AI Agent", "database_entity": "Shipment", "kpi_name": "On-time Delivery", "kpi_formula": "(on_time_deliveries / total_deliveries) * 100", "kpi_target": 95, "kpi_unit": "%", "compliance_framework": "ISO", "compliance_standard": "ISO 28000", "regulatory_reference": "ISO 28000:2022"},
            {"industry_id": "LOG", "control_id": "LOG-RTG-001", "module": "Routing", "control_name": "Route Optimization", "sub_control": "Delivery Routes", "description": "Delivery route optimization and planning", "control_type": "operational", "is_required": False, "severity": "low", "ai_agent_name": "Route AI Agent", "database_entity": "DeliveryRoute", "kpi_name": "Route Efficiency", "kpi_formula": "(optimal_distance / actual_distance) * 100", "kpi_target": 90, "kpi_unit": "%", "compliance_framework": "ISO", "compliance_standard": "ISO 28000", "regulatory_reference": "ISO 28000:2022"},

            # Automotive
            {"industry_id": "AUTO", "control_id": "AUTO-ASM-001", "module": "Assembly", "control_name": "Assembly Line Control", "sub_control": "Quality Gates", "description": "Assembly line quality control and monitoring", "control_type": "quality", "is_required": True, "severity": "high", "ai_agent_name": "Assembly AI Agent", "database_entity": "AssemblyStation", "kpi_name": "First Pass Yield", "kpi_formula": "(passed_first_time / total_units) * 100", "kpi_target": 98, "kpi_unit": "%", "compliance_framework": "IATF", "compliance_standard": "IATF 16949", "regulatory_reference": "IATF 16949:2016"},
            {"industry_id": "AUTO", "control_id": "AUTO-TRC-001", "module": "Traceability", "control_name": "Parts Traceability", "sub_control": "VIN Tracking", "description": "Vehicle and parts traceability system", "control_type": "quality", "is_required": True, "severity": "high", "ai_agent_name": "Traceability AI Agent", "database_entity": "Vehicle", "kpi_name": "Traceability Coverage", "kpi_formula": "(traceable_parts / total_parts) * 100", "kpi_target": 100, "kpi_unit": "%", "compliance_framework": "IATF", "compliance_standard": "IATF 16949", "regulatory_reference": "IATF 16949:2016"},
        ]

        created_count = 0
        for ctrl_data in controls_data:
            try:
                industry = IndustryCatalog.objects.get(industry_id=ctrl_data["industry_id"])
                obj, created = IndustryControl.objects.update_or_create(
                    industry=industry,
                    control_id=ctrl_data["control_id"],
                    defaults={k: v for k, v in ctrl_data.items() if k != "industry_id"}
                )
                if created:
                    created_count += 1
            except IndustryCatalog.DoesNotExist:
                pass

        self.stdout.write(self.style.SUCCESS(f'Created {created_count} controls'))

    def seed_ai_agents(self):
        self.stdout.write('Seeding AI agents...')

        agents_data = [
            {"industry_id": "AVI", "agent_id": "AVI-FLT-AI", "name": "Flight AI Agent", "name_ar": "وكيل الطيران الذكي", "agent_type": "automation", "description": "Flight planning and operations optimization", "responsibilities": ["Route optimization", "Fuel efficiency", "Weather analysis"], "database_entities": ["Flight", "Route", "Weather"]},
            {"industry_id": "AVI", "agent_id": "AVI-MNT-AI", "name": "Maintenance AI Agent", "name_ar": "وكيل الصيانة الذكي", "agent_type": "predictive", "description": "Predictive aircraft maintenance", "responsibilities": ["Failure prediction", "Maintenance scheduling", "Parts inventory"], "database_entities": ["MaintenanceOrder", "Aircraft", "Part"]},
            {"industry_id": "AVI", "agent_id": "AVI-SAF-AI", "name": "Safety AI Agent", "name_ar": "وكيل السلامة الذكي", "agent_type": "monitoring", "description": "Safety incident monitoring and prevention", "responsibilities": ["Incident detection", "Risk assessment", "Safety reporting"], "database_entities": ["SafetyIncident", "RiskAssessment"]},
            {"industry_id": "HLT", "agent_id": "HLT-CLN-AI", "name": "Clinical AI Agent", "name_ar": "وكيل الرعاية السريرية الذكي", "agent_type": "analytical", "description": "Clinical assistance and diagnosis support", "responsibilities": ["Diagnosis support", "Treatment recommendations", "Drug interactions"], "database_entities": ["MedicalRecord", "Diagnosis", "Prescription"]},
            {"industry_id": "HLT", "agent_id": "HLT-PHR-AI", "name": "Pharmacy AI Agent", "name_ar": "وكيل الصيدلة الذكي", "agent_type": "automation", "description": "Pharmacy automation and verification", "responsibilities": ["Prescription verification", "Drug dispensing", "Inventory management"], "database_entities": ["Prescription", "Medication", "Inventory"]},
            {"industry_id": "MFG", "agent_id": "MFG-PRO-AI", "name": "Production AI Agent", "name_ar": "وكيل الإنتاج الذكي", "agent_type": "automation", "description": "Production optimization and scheduling", "responsibilities": ["Production scheduling", "Quality prediction", "Resource allocation"], "database_entities": ["ProductionOrder", "WorkCenter", "BOM"]},
            {"industry_id": "MFG", "agent_id": "MFG-QA-AI", "name": "Quality AI Agent", "name_ar": "وكيل الجودة الذكي", "agent_type": "analytical", "description": "Quality inspection and defect detection", "responsibilities": ["Defect detection", "Quality analysis", "Process improvement"], "database_entities": ["Inspection", "Defect", "QualityReport"]},
            {"industry_id": "BANK", "agent_id": "BANK-KYC-AI", "name": "KYC AI Agent", "name_ar": "وكيل التحقق من العملاء الذكي", "agent_type": "automation", "description": "Automated KYC verification and due diligence", "responsibilities": ["Identity verification", "Risk scoring", "Document analysis"], "database_entities": ["Customer", "Verification", "RiskProfile"]},
            {"industry_id": "BANK", "agent_id": "BANK-AML-AI", "name": "AML AI Agent", "name_ar": "وكيل مكافحة غسيل الأموال الذكي", "agent_type": "monitoring", "description": "Anti-money laundering transaction monitoring", "responsibilities": ["Transaction monitoring", "Alert generation", "Pattern detection"], "database_entities": ["Transaction", "Alert", "CustomerProfile"]},
            {"industry_id": "BANK", "agent_id": "BANK-CRD-AI", "name": "Credit AI Agent", "name_ar": "وكيل الائتمان الذكي", "agent_type": "predictive", "description": "Credit risk assessment and scoring", "responsibilities": ["Credit scoring", "Risk assessment", "Default prediction"], "database_entities": ["CreditApplication", "Loan", "CreditScore"]},
            {"industry_id": "BANK", "agent_id": "BANK-FRD-AI", "name": "Fraud AI Agent", "name_ar": "وكيل مكافحة الاحتيال الذكي", "agent_type": "monitoring", "description": "Real-time fraud detection and prevention", "responsibilities": ["Fraud detection", "Transaction blocking", "Investigation support"], "database_entities": ["Transaction", "FraudAlert", "Investigation"]},
            {"industry_id": "OIL", "agent_id": "OIL-HSE-AI", "name": "HSE AI Agent", "name_ar": "وكيل الصحة والسلامة الذكي", "agent_type": "monitoring", "description": "HSE incident monitoring and prevention", "responsibilities": ["Incident detection", "Risk assessment", "Compliance monitoring"], "database_entities": ["HSEIncident", "RiskAssessment", "ComplianceRecord"]},
            {"industry_id": "OIL", "agent_id": "OIL-RES-AI", "name": "Reservoir AI Agent", "name_ar": "وكيل المخزون النفطي الذكي", "agent_type": "predictive", "description": "Reservoir performance prediction and optimization", "responsibilities": ["Production forecasting", "Reservoir modeling", "Recovery optimization"], "database_entities": ["Reservoir", "Well", "ProductionData"]},
            {"industry_id": "ENE", "agent_id": "ENE-GRD-AI", "name": "Grid AI Agent", "name_ar": "وكيل الشبكة الذكي", "agent_type": "automation", "description": "Smart grid management and optimization", "responsibilities": ["Load balancing", "Outage prediction", "Demand forecasting"], "database_entities": ["GridNode", "Load", "Outage"]},
            {"industry_id": "ENE", "agent_id": "ENE-SLR-AI", "name": "Solar AI Agent", "name_ar": "وكيل الطاقة الشمسية الذكي", "agent_type": "predictive", "description": "Solar panel performance optimization", "responsibilities": ["Performance prediction", "Maintenance scheduling", "Efficiency analysis"], "database_entities": ["SolarPanel", "Inverter", "Weather"]},
            {"industry_id": "ENE", "agent_id": "ENE-WND-AI", "name": "Wind AI Agent", "name_ar": "وكيل طاقة الرياح الذكي", "agent_type": "predictive", "description": "Wind turbine performance optimization", "responsibilities": ["Power forecasting", "Maintenance optimization", "Turbine control"], "database_entities": ["WindTurbine", "WindFarm", "Weather"]},
            {"industry_id": "RET", "agent_id": "RET-INV-AI", "name": "Inventory AI Agent", "name_ar": "وكيل المخزون الذكي", "agent_type": "predictive", "description": "Inventory demand forecasting and optimization", "responsibilities": ["Demand forecasting", "Stock optimization", "Reorder automation"], "database_entities": ["InventoryItem", "SalesOrder", "PurchaseOrder"]},
            {"industry_id": "ECOM", "agent_id": "ECOM-SEO-AI", "name": "SEO AI Agent", "name_ar": "وكيل تحسين محركات البحث الذكي", "agent_type": "analytical", "description": "SEO performance analysis and optimization", "responsibilities": ["Keyword analysis", "Content optimization", "Ranking prediction"], "database_entities": ["Page", "Keyword", "Ranking"]},
            {"industry_id": "CON", "agent_id": "CON-PRJ-AI", "name": "Project AI Agent", "name_ar": "وكيل المشاريع الذكي", "agent_type": "automation", "description": "Construction project management and optimization", "responsibilities": ["Schedule optimization", "Resource allocation", "Cost control"], "database_entities": ["Project", "Task", "Resource"]},
            {"industry_id": "FNB", "agent_id": "FNB-SAF-AI", "name": "Food Safety AI Agent", "name_ar": "وكيل سلامة الغذاء الذكي", "agent_type": "monitoring", "description": "Food safety compliance monitoring", "responsibilities": ["HACCP monitoring", "Temperature tracking", "Contamination detection"], "database_entities": ["HACCPRecord", "TemperatureLog", "BatchRecord"]},
            {"industry_id": "INS", "agent_id": "INS-UND-AI", "name": "Underwriting AI Agent", "name_ar": "وكيل التأمين الذكي", "agent_type": "predictive", "description": "Automated insurance underwriting", "responsibilities": ["Risk assessment", "Premium calculation", "Policy recommendation"], "database_entities": ["PolicyApplication", "RiskProfile", "Premium"]},
            {"industry_id": "INS", "agent_id": "INS-CLM-AI", "name": "Claims AI Agent", "name_ar": "وكيل المطالبات الذكي", "agent_type": "automation", "description": "Automated claims processing and fraud detection", "responsibilities": ["Claims processing", "Fraud detection", "Settlement calculation"], "database_entities": ["Claim", "Policy", "Settlement"]},
            {"industry_id": "GOV", "agent_id": "GOV-SEC-AI", "name": "Security AI Agent", "name_ar": "وكيل الأمن الذكي", "agent_type": "monitoring", "description": "Government security monitoring and threat detection", "responsibilities": ["Threat detection", "Access monitoring", "Incident response"], "database_entities": ["SecurityIncident", "AccessLog", "Threat"]},
            {"industry_id": "LOG", "agent_id": "LOG-TRK-AI", "name": "Tracking AI Agent", "name_ar": "وكيل التتبع الذكي", "agent_type": "automation", "description": "Real-time shipment tracking and ETA prediction", "responsibilities": ["ETA prediction", "Route optimization", "Delay detection"], "database_entities": ["Shipment", "Route", "Delivery"]},
            {"industry_id": "AUTO", "agent_id": "AUTO-ASM-AI", "name": "Assembly AI Agent", "name_ar": "وكيل التجميع الذكي", "agent_type": "automation", "description": "Assembly line optimization and quality control", "responsibilities": ["Line balancing", "Quality prediction", "Defect detection"], "database_entities": ["AssemblyStation", "QualityCheck", "Defect"]},
        ]

        created_count = 0
        for agent_data in agents_data:
            try:
                industry = IndustryCatalog.objects.get(industry_id=agent_data["industry_id"])
                obj, created = AIAgentRegistry.objects.update_or_create(
                    industry=industry,
                    agent_id=agent_data["agent_id"],
                    defaults={k: v for k, v in agent_data.items() if k not in ["industry_id", "agent_id"]}
                )
                if created:
                    created_count += 1
            except IndustryCatalog.DoesNotExist:
                pass

        self.stdout.write(self.style.SUCCESS(f'Created {created_count} AI agents'))
