# Generated by Django 4.2.30 on 2026-07-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aiconversation_aiknowledgebase_aiprompttemplate_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='stockentry', name='created_by'),
        migrations.AddField(model_name='stockentry', name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
    ]
