# Generated by Django 4.2.30 on 2026-07-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aiconversation_aiknowledgebase_aiprompttemplate_and_more'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='employee', name='user'),
        migrations.AddField(model_name='employee', name='user',
            field=models.OneToOneField(blank=True, help_text='Login account for this employee, used to scope "my tasks".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to='core.user'),
        ),
    ]
