# Generated by Django 4.2.30 on 2026-07-06 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_uiscreen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Version')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Author')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Author Email')),
                ('module_path', models.CharField(max_length=500, verbose_name='Module Path')),
                ('entry_point', models.CharField(default='plugin', max_length=200, verbose_name='Entry Point')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Review'), ('rejected', 'Rejected'), ('deprecated', 'Deprecated')], default='pending', max_length=20, verbose_name='Status')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Is Premium')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('icon', models.URLField(blank=True, verbose_name='Icon')),
                ('screenshots', models.JSONField(blank=True, default=list, verbose_name='Screenshots')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Rating')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Review Count')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('permissions_required', models.JSONField(blank=True, default=list, verbose_name='Permissions Required')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PluginHook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Hook Name')),
                ('event', models.CharField(max_length=200, verbose_name='Event')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('hook_type', models.CharField(choices=[('action', 'Action'), ('filter', 'Filter'), ('event', 'Event')], default='action', max_length=20, verbose_name='Hook Type')),
                ('handler_path', models.CharField(max_length=500, verbose_name='Handler Path')),
                ('priority', models.PositiveIntegerField(default=10, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Plugin Hook',
                'verbose_name_plural': 'Plugin Hooks',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PluginMarketReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PluginRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Version')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Author')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Author Email')),
                ('module_path', models.CharField(max_length=500, verbose_name='Module Path')),
                ('entry_point', models.CharField(default='plugin', max_length=200, verbose_name='Entry Point')),
                ('source_code_hash', models.CharField(blank=True, max_length=64, verbose_name='Source Hash')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('deprecated', 'Deprecated'), ('uninstalled', 'Uninstalled')], default='pending', max_length=20)),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Is Premium')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('icon', models.CharField(blank=True, max_length=200, verbose_name='Icon URL')),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('manifest', models.JSONField(default=dict, verbose_name='Manifest')),
                ('dependencies', models.JSONField(default=list, verbose_name='Dependencies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-download_count', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='TenantPluginInstall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('deprecated', 'Deprecated'), ('uninstalled', 'Uninstalled')], default='pending', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('uninstalled_at', models.DateTimeField(blank=True, null=True)),
                ('installed_version', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_installations', to='plugins.pluginregistry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_installs', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantPlugin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('installed', 'Installed'), ('active', 'Active'), ('paused', 'Paused'), ('uninstalled', 'Uninstalled')], default='installed', max_length=20, verbose_name='Status')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='Paid Until')),
                ('installed_at', models.DateTimeField(auto_now_add=True, verbose_name='Installed At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_installations', to='plugins.plugin', verbose_name='Plugin')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tenant Plugin',
                'verbose_name_plural': 'Tenant Plugins',
                'ordering': ['-installed_at'],
            },
        ),
        migrations.CreateModel(
            name='PluginSandbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowed_modules', models.JSONField(default=list, help_text='Allowed Python modules')),
                ('allowed_apis', models.JSONField(default=list, help_text='Allowed API endpoints')),
                ('max_execution_time', models.PositiveIntegerField(default=30, help_text='Max execution time in seconds')),
                ('max_memory_mb', models.PositiveIntegerField(default=128)),
                ('execution_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandboxes', to='plugins.pluginregistry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_sandboxes', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PluginReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='plugins.plugin', verbose_name='Plugin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pluginregistry',
            index=models.Index(fields=['status', 'is_published'], name='plugins_plu_status_63af46_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginregistry',
            index=models.Index(fields=['category'], name='plugins_plu_categor_6ab079_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginregistry',
            index=models.Index(fields=['slug', 'version'], name='plugins_plu_slug_467d54_idx'),
        ),
        migrations.AddField(
            model_name='pluginmarketreview',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='plugins.pluginregistry'),
        ),
        migrations.AddField(
            model_name='pluginmarketreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='pluginhook',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='plugins.plugin', verbose_name='Plugin'),
        ),
        migrations.AddIndex(
            model_name='tenantplugininstall',
            index=models.Index(fields=['tenant', 'status'], name='plugins_ten_tenant__540d44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantplugininstall',
            unique_together={('tenant', 'plugin')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantplugin',
            unique_together={('tenant', 'plugin')},
        ),
        migrations.AlterUniqueTogether(
            name='pluginreview',
            unique_together={('plugin', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='pluginmarketreview',
            unique_together={('plugin', 'user')},
        ),
    ]
