# Generated by Django 4.2.30 on 2026-07-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenantmembership_invited_by_and_more'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='pluginreview', name='user'),
        migrations.AddField(model_name='pluginreview', name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_reviews', to='tenants.tenantuser', verbose_name='User'),
        ),
    ]
