# docker-compose.secrets.yml
# Use this for production with Docker Swarm or Kubernetes

version: "3.9"

secrets:
  django_secret_key:
    external: true
  db_password:
    external: true
  ssl_certificate:
    external: true
  ssl_key:
    external: true

services:
  backend:
    secrets:
      - source: django_secret_key
        target: /run/secrets/secret_key
      - source: db_password
        target: /run/secrets/db_password
    environment:
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - DB_PASSWORD_FILE=/run/secrets/db_password
