# Generated by Django 4.2.30 on 2026-07-07 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_sagainstance_projection_outboxevent_multiregionsync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('off_track', 'Off Track'), ('exceeded', 'Exceeded')], default='on_track', max_length=20)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='core.company')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('kpi_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('operational', 'Operational'), ('quality', 'Quality'), ('safety', 'Safety'), ('customer', 'Customer'), ('employee', 'Employee'), ('environmental', 'Environmental')], default='operational', max_length=20)),
                ('description', models.TextField()),
                ('formula', models.CharField(blank=True, max_length=500)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('min_acceptable', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('max_acceptable', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('data_source', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KPI Definition',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('company_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kpi.companykpi')),
            ],
            options={
                'verbose_name': 'KPI History',
                'verbose_name_plural': 'KPI Histories',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('chart_line', 'Line Chart'), ('chart_bar', 'Bar Chart'), ('chart_pie', 'Pie Chart'), ('metric', 'Metric'), ('table', 'Table'), ('gauge', 'Gauge'), ('list', 'List')], default='metric', max_length=20)),
                ('data_source', models.CharField(blank=True, max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=4)),
                ('height', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='core.company')),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.AddField(
            model_name='companykpi',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_records', to='kpi.kpidefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='companykpi',
            unique_together={('company', 'kpi')},
        ),
    ]
