# Generated by Django 4.2.30 on 2026-07-06 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('messages', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('embedding_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField()),
                ('variables', models.JSONField(default=list, help_text='List of required variables')),
                ('module', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, help_text='Cached email in case user is deleted', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('PRINT', 'Print'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changes_diff', models.JSONField(blank=True, default=dict, help_text='Computed diff between old and new')),
                ('company_id', models.PositiveIntegerField(blank=True, null=True)),
                ('branch_id', models.PositiveIntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('request_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(default=dict)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateMachineInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('document_id', models.CharField(max_length=100)),
                ('tenant_id', models.CharField(max_length=100)),
                ('current_state', models.CharField(max_length=100)),
                ('previous_state', models.CharField(blank=True, max_length=100)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(model_name='auditlog', name='user'),
        migrations.AddField(model_name='auditlog', name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='core.user'),
        ),
        migrations.CreateModel(
            name='SystemImprovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('improvement_type', models.CharField(choices=[('workflow_optimization', 'Workflow Optimization'), ('rule_adjustment', 'Rule Adjustment'), ('automation_addition', 'Automation Addition'), ('ui_enhancement', 'Ui Enhancement'), ('performance_tuning', 'Performance Tuning'), ('security_hardening', 'Security Hardening'), ('data_quality', 'Data Quality')], max_length=50)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('analyzing', 'Analyzing'), ('suggested', 'Suggested'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('deployed', 'Deployed'), ('rolled_back', 'Rolled Back'), ('rejected', 'Rejected')], default='detected', max_length=50)),
                ('analysis_data', models.JSONField(default=dict)),
                ('suggestion_data', models.JSONField(default=dict)),
                ('expected_impact', models.TextField(blank=True)),
                ('implementation_steps', models.JSONField(default=list)),
                ('risk_assessment', models.TextField(blank=True)),
                ('rollback_plan', models.TextField(blank=True)),
                ('proposed_by', models.CharField(default='AI', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StateTransitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(max_length=100)),
                ('to_state', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('triggered_by_role', models.CharField(blank=True, max_length=50)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('guard_results', models.JSONField(blank=True, default=dict)),
                ('side_effects_executed', models.JSONField(blank=True, default=list)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_logs', to='core.statemachineinstance')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='statemachineinstance',
            index=models.Index(fields=['document_type', 'document_id', 'tenant_id'], name='core_statem_documen_8695da_idx'),
        ),
        migrations.AddIndex(
            model_name='statemachineinstance',
            index=models.Index(fields=['current_state', 'is_active'], name='core_statem_current_cd55e7_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['metric_name', 'recorded_at'], name='core_perfor_metric__a35515_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['tags'], name='core_perfor_tags_3a2054_idx'),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiknowledgebase',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_knowledge', to='core.company'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='core.user'),
        ),
        migrations.AddIndex(
            model_name='statetransitionlog',
            index=models.Index(fields=['state_machine', 'created_at'], name='core_statet_state_m_4037fd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_978442_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['model_name', '-timestamp'], name='core_auditl_model_n_af4555_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['action', '-timestamp'], name='core_auditl_action_d9d6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['company_id', '-timestamp'], name='core_auditl_company_622f03_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgebase',
            index=models.Index(fields=['company', 'category'], name='core_aiknow_company_770ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgebase',
            index=models.Index(fields=['company', 'tags'], name='core_aiknow_company_af29a4_idx'),
        ),
    ]
