# Generated by Django 4.2.30 on 2026-07-06 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aiconversation_aiknowledgebase_aiprompttemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('title_ar', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(default=dict, help_text='{"fields": [{"name","type","label","label_ar","required","options","default"}], "layout": "single|two-col"}')),
                ('target_endpoint', models.CharField(blank=True, help_text='API path form submissions POST to, e.g. /api/v1/crm/leads/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_screens', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('company', 'slug')},
            },
        ),
    ]
