# Generated by Django 4.2.30 on 2026-07-07 00:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_uiscreen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.BigIntegerField(db_index=True, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_hash', models.CharField(max_length=64)),
                ('entry_hash', models.CharField(max_length=64, unique=True)),
                ('signature', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(db_index=True, max_length=50)),
                ('ref_id', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('company_id', models.IntegerField(db_index=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'unique_together': {('node_type', 'ref_id')},
            },
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(db_index=True, max_length=50)),
                ('weight', models.FloatField(default=1.0)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='core.graphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='core.graphnode')),
            ],
            options={
                'unique_together': {('source', 'target', 'relation')},
            },
        ),
    ]
