# Generated by Django 4.2.30 on 2026-07-07 01:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditledgerentry_graphnode_graphedge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SagaInstance',
            fields=[
                ('saga_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('saga_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('started', 'Started'), ('running', 'Running'), ('completed', 'Completed'), ('compensating', 'Compensating'), ('compensated', 'Compensated'), ('failed', 'Failed')], default='started', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('steps_data', models.JSONField(default=list)),
                ('compensation_data', models.JSONField(default=list)),
                ('context', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'saga_instances',
                'indexes': [models.Index(fields=['saga_type', 'status'], name='saga_instan_saga_ty_5ab868_idx'), models.Index(fields=['tenant_id', 'status'], name='saga_instan_tenant__0530bc_idx'), models.Index(fields=['started_at'], name='saga_instan_started_ab8504_idx')],
            },
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('projection_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('projection_name', models.CharField(db_index=True, max_length=255)),
                ('projection_type', models.CharField(max_length=100)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('version', models.PositiveIntegerField(default=0)),
                ('is_stale', models.BooleanField(default=False)),
                ('last_event_timestamp', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projections',
                'indexes': [models.Index(fields=['projection_name', 'aggregate_type'], name='projections_project_ea78d2_idx'), models.Index(fields=['aggregate_id', 'projection_name'], name='projections_aggrega_b2985f_idx'), models.Index(fields=['is_stale', 'updated_at'], name='projections_is_stal_f3e28d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('destination_topic', models.CharField(max_length=255)),
                ('partition_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
            ],
            options={
                'db_table': 'outbox_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['processed_at', 'created_at'], name='outbox_even_process_d5bcb9_idx'), models.Index(fields=['destination_topic', 'processed_at'], name='outbox_even_destina_e973e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MultiRegionSync',
            fields=[
                ('sync_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source_region', models.CharField(max_length=50)),
                ('target_region', models.CharField(max_length=50)),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental'), ('conflict_resolution', 'Conflict Resolution')], max_length=20)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('data_hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('conflict_detected', models.BooleanField(default=False)),
                ('conflict_resolution', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'multi_region_sync',
                'indexes': [models.Index(fields=['source_region', 'target_region'], name='multi_regio_source__00b1ba_idx'), models.Index(fields=['entity_type', 'status'], name='multi_regio_entity__28f3fd_idx'), models.Index(fields=['synced_at'], name='multi_regio_synced__2c8639_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('aggregate_type', models.CharField(db_index=True, max_length=100)),
                ('version', models.PositiveIntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('command', 'Command'), ('snapshot', 'Snapshot')], max_length=50)),
                ('event_data', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'event_store',
                'ordering': ['aggregate_id', 'version'],
                'indexes': [models.Index(fields=['aggregate_type', 'timestamp'], name='event_store_aggrega_11abe1_idx'), models.Index(fields=['tenant_id', 'timestamp'], name='event_store_tenant__08c74a_idx'), models.Index(fields=['event_type', 'timestamp'], name='event_store_event_t_46c219_idx'), models.Index(fields=['region', 'timestamp'], name='event_store_region_5101b4_idx')],
                'unique_together': {('aggregate_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DistributedLock',
            fields=[
                ('lock_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=50)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_released', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'distributed_locks',
                'indexes': [models.Index(fields=['expires_at', 'is_released'], name='distributed_expires_5f269c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AggregateSnapshot',
            fields=[
                ('aggregate_id', models.UUIDField(primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('state', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
            ],
            options={
                'db_table': 'aggregate_snapshots',
                'indexes': [models.Index(fields=['aggregate_type', 'updated_at'], name='aggregate_s_aggrega_7b63c6_idx')],
            },
        ),
    ]
