# Generated by Django 4.2.30 on 2026-07-07 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sagainstance_projection_outboxevent_multiregionsync_and_more'),
    ]

    operations = [
        migrations.RemoveField(model_name='auditlogentry', name='user'),
        migrations.AddField(model_name='auditlogentry', name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
