# Generated by Django 4.2.30 on 2026-07-07 01:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_sagainstance_projection_outboxevent_multiregionsync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHandler',
            fields=[
                ('handler_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('handler_name', models.CharField(max_length=255)),
                ('event_names', models.JSONField(default=list)),
                ('handler_type', models.CharField(choices=[('sync', 'Synchronous'), ('async', 'Asynchronous'), ('scheduled', 'Scheduled')], default='sync', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('retry_policy', models.JSONField(blank=True, default=dict)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('avg_processing_time_ms', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Handler',
                'ordering': ['handler_name'],
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subscription_type', models.CharField(choices=[('webhook', 'Webhook'), ('sqs', 'AWS SQS'), ('sns', 'AWS SNS'), ('kafka', 'Kafka Topic'), ('redis', 'Redis Pub/Sub')], max_length=20)),
                ('endpoint', models.CharField(max_length=500)),
                ('event_filter', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveIntegerField(default=3)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SagaInstance',
            fields=[
                ('saga_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('saga_type', models.CharField(db_index=True, max_length=100)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('compensating', 'Compensating'), ('compensated', 'Compensated'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('steps_log', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Saga Instance',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['saga_type', 'state'], name='events_saga_saga_ty_0b4e53_idx'), models.Index(fields=['correlation_id'], name='events_saga_correla_84692a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventStore',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('domain', 'Domain Event'), ('integration', 'Integration Event'), ('system', 'System Event'), ('audit', 'Audit Event')], default='domain', max_length=50)),
                ('aggregate_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_id', models.CharField(db_index=True, max_length=100)),
                ('event_name', models.CharField(db_index=True, max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Event Store',
                'verbose_name_plural': 'Event Stores',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id', 'version'], name='events_even_aggrega_f705d0_idx'), models.Index(fields=['event_name', 'timestamp'], name='events_even_event_n_61d41c_idx'), models.Index(fields=['correlation_id'], name='events_even_correla_f0c776_idx'), models.Index(fields=['tenant_id', 'timestamp'], name='events_even_tenant__021297_idx'), models.Index(fields=['processed', 'error_count'], name='events_even_process_924d58_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventProjection',
            fields=[
                ('projection_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('projection_name', models.CharField(db_index=True, max_length=200)),
                ('aggregate_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_id', models.CharField(db_index=True, max_length=100)),
                ('state', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('is_stale', models.BooleanField(default=False)),
                ('last_event_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Projection',
                'indexes': [models.Index(fields=['projection_name', 'is_stale'], name='events_even_project_377224_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='events_even_aggrega_08ac5a_idx')],
                'unique_together': {('projection_name', 'aggregate_type', 'aggregate_id')},
            },
        ),
        migrations.CreateModel(
            name='DeadLetterQueue',
            fields=[
                ('dlq_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('error_message', models.TextField()),
                ('error_stack', models.TextField(blank=True)),
                ('handler_id', models.CharField(blank=True, max_length=200)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlq_entries', to='events.eventstore')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'verbose_name': 'Dead Letter Queue',
                'verbose_name_plural': 'Dead Letter Queues',
                'ordering': ['-created_at'],
            },
        ),
    ]
