# Generated by Django 4.2.30 on 2026-07-05 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=18)),
                ('uom', models.CharField(default='Unit', max_length=50)),
                ('operating_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='core.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(max_length=100, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('qty_to_produce', models.DecimalField(decimal_places=2, max_digits=18)),
                ('produced_qty', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('uom', models.CharField(default='Unit', max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.bom')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='core.company')),
                ('item_to_manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('uom', models.CharField(default='Unit', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manufacturing.bom')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
    ]
