# Generated by Django 4.2.30 on 2026-07-06 20:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Invoice ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Payment Intent ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('uncollectible', 'Uncollectible'), ('void', 'Void')], default='draft', max_length=20, verbose_name='Status')),
                ('invoice_date', models.DateTimeField(auto_now_add=True, verbose_name='Invoice Date')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('line_items', models.JSONField(default=list, verbose_name='Line Items')),
                ('pdf_url', models.URLField(blank=True, verbose_name='PDF URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20, verbose_name='Billing Interval')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('stripe_product_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Product ID')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Price ID')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Features')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='Max Users')),
                ('max_storage_mb', models.PositiveIntegerField(default=100, verbose_name='Max Storage (MB)')),
                ('max_projects', models.PositiveIntegerField(default=10, verbose_name='Max Projects')),
                ('api_calls_per_month', models.PositiveIntegerField(default=10000, verbose_name='API Calls/Month')),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='starter', max_length=20, verbose_name='Plan Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is Public')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_type', models.CharField(choices=[('api_call', 'API Call'), ('storage', 'Storage (MB)'), ('bandwidth', 'Bandwidth (MB)'), ('user', 'User'), ('project', 'Project'), ('plugin', 'Plugin')], max_length=20, verbose_name='Usage Type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Quantity')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('billing_period_start', models.DateTimeField(verbose_name='Billing Period Start')),
                ('billing_period_end', models.DateTimeField(verbose_name='Billing Period End')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Usage Record',
                'verbose_name_plural': 'Usage Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Subscription ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Customer ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='trialing', max_length=20, verbose_name='Status')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Current Period Start')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Current Period End')),
                ('trial_start', models.DateTimeField(blank=True, null=True, verbose_name='Trial Start')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='Trial End')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Cancel at Period End')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='Plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Payment Intent')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Charge ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')], default='card', max_length=20, verbose_name='Payment Method')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Card Last 4')),
                ('card_brand', models.CharField(blank=True, max_length=50, verbose_name='Card Brand')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice', verbose_name='Invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.subscription', verbose_name='Subscription'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
