# Generated by Django 4.2.30 on 2026-07-05 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('allowed_roles', models.CharField(blank=True, max_length=255)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='workflow.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='workflow.workflowstate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflow')),
            ],
        ),
    ]
