# Generated by Django 4.2.30 on 2026-07-06 19:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aiconversation_aiknowledgebase_aiprompttemplate_and_more'),
        ('tenants', '__first__'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rolling_back', 'Rolling_Back'), ('rolled_back', 'Rolled_Back')], default='pending', max_length=20)),
                ('tenant_id', models.CharField(max_length=100)),
                ('variables', models.JSONField(default=dict, verbose_name='Process Variables')),
                ('context_data', models.JSONField(default=dict, verbose_name='Context Data')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('rollback_data', models.JSONField(blank=True, default=dict)),
                ('parent_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_processes', to='workflow.processinstance')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('bpmn_xml', models.TextField(blank=True, verbose_name='BPMN XML')),
                ('nodes', models.JSONField(default=list, verbose_name='Nodes')),
                ('edges', models.JSONField(default=list, verbose_name='Edges')),
                ('document_type', models.CharField(blank=True, max_length=100, verbose_name='Document Type')),
                ('module', models.CharField(blank=True, max_length=50, verbose_name='Module')),
                ('trigger_types', models.JSONField(default=list, verbose_name='Trigger Types')),
                ('trigger_config', models.JSONField(default=dict, verbose_name='Trigger Config')),
                ('state_machine_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=100)),
                ('node_name', models.CharField(blank=True, max_length=200)),
                ('node_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('timed_out', 'Timed_Out')], default='pending', max_length=20)),
                ('assigned_role', models.CharField(blank=True, max_length=50)),
                ('candidate_users', models.JSONField(blank=True, default=list)),
                ('candidate_groups', models.JSONField(blank=True, default=list)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('rollback_actions', models.JSONField(blank=True, default=list)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.processinstance')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.AddField(
            model_name='processinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflow.workflowdefinition'),
        ),
        migrations.CreateModel(
            name='ProcessHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow.processinstance')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.taskinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Execution order in the chain')),
                ('approver_role', models.CharField(blank=True, help_text='Role-based approver if no specific user', max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('auto_approve_if', models.TextField(blank=True, help_text='Conditions for auto-approval (JSON logic)')),
                ('timeout_hours', models.PositiveIntegerField(default=48, help_text='Hours before escalation')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='core.user')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='workflow.workflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Escalated', 'Escalated'), ('Skipped', 'Skipped')], default='Pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='core.user')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.user')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='workflow.approvalstep')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['slug', 'is_latest'], name='workflow_wo_slug_0a1928_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['document_type', 'is_active'], name='workflow_wo_documen_707db4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdefinition',
            unique_together={('slug', 'version', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['process', 'status'], name='workflow_ta_process_8b9ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['assigned_to', 'status'], name='workflow_ta_assigne_f2b4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['due_date'], name='workflow_ta_due_dat_962a68_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['workflow', 'status'], name='workflow_pr_workflo_e52d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['tenant_id', 'status'], name='workflow_pr_tenant__e887d4_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['started_at'], name='workflow_pr_started_ef22ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('workflow', 'order')},
        ),
    ]
