# Generated by Django 4.2.30 on 2026-07-06 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aiconversation_aiknowledgebase_aiprompttemplate_and_more'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('name_ar', models.CharField(blank=True, max_length=60)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('decimals', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.RemoveField(model_name='journalentry', name='posted_by'),
        migrations.AddField(model_name='journalentry', name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to='core.user'),
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='SA', max_length=2)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT'), ('withholding', 'Withholding'), ('excise', 'Excise'), ('zero', 'Zero-rated'), ('exempt', 'Exempt')], default='vat', max_length=15)),
                ('category', models.CharField(blank=True, help_text='Item/service category; blank = all', max_length=60)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(blank=True, help_text='GL account for this tax', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('company', models.ForeignKey(blank=True, help_text='Null = global default rule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='core.company')),
            ],
            options={
                'ordering': ['country', 'category'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.journalentry')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='core.company')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounts.fiscalyear')),
            ],
            options={
                'ordering': ['fiscal_year', 'number'],
                'unique_together': {('fiscal_year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='accounts.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='accounts.currency')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
    ]
