# Generated by Django 4.2.30 on 2026-07-07 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_sagainstance_projection_outboxevent_multiregionsync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCatalog',
            fields=[
                ('industry_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='Building2', max_length=100)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('required_license_tier', models.CharField(choices=[('starter', 'Starter'), ('business', 'Business'), ('industry', 'Industry'), ('enterprise', 'Enterprise AI')], default='starter', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Industry Catalog',
                'verbose_name_plural': 'Industry Catalogs',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndustryControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(db_index=True, max_length=50)),
                ('module', models.CharField(max_length=100)),
                ('control_name', models.CharField(max_length=255)),
                ('control_name_ar', models.CharField(blank=True, max_length=255)),
                ('sub_control', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('control_type', models.CharField(choices=[('operational', 'Operational'), ('financial', 'Financial'), ('compliance', 'Compliance'), ('safety', 'Safety'), ('quality', 'Quality'), ('environmental', 'Environmental'), ('security', 'Security'), ('hr', 'Human Resources')], default='operational', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('ai_agent_name', models.CharField(blank=True, max_length=100)),
                ('ai_agent_description', models.TextField(blank=True)),
                ('database_entity', models.CharField(blank=True, max_length=100)),
                ('kpi_name', models.CharField(blank=True, max_length=100)),
                ('kpi_formula', models.CharField(blank=True, max_length=255)),
                ('kpi_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kpi_unit', models.CharField(blank=True, max_length=50)),
                ('compliance_framework', models.CharField(blank=True, max_length=100)),
                ('compliance_standard', models.CharField(blank=True, max_length=100)),
                ('regulatory_reference', models.CharField(blank=True, max_length=255)),
                ('implementation_guide', models.TextField(blank=True)),
                ('implementation_guide_ar', models.TextField(blank=True)),
                ('automation_rules', models.JSONField(blank=True, default=dict)),
                ('checklists', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='industries.industrycatalog')),
            ],
            options={
                'verbose_name': 'Industry Control',
                'verbose_name_plural': 'Industry Controls',
                'ordering': ['industry', 'sort_order', 'control_id'],
                'unique_together': {('industry', 'control_id')},
            },
        ),
        migrations.CreateModel(
            name='ControlExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('findings', models.TextField(blank=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('remediation_notes', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_logs', to='core.company')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='industries.industrycontrol')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'verbose_name': 'Control Execution Log',
                'verbose_name_plural': 'Control Execution Logs',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAgentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('agent_type', models.CharField(choices=[('predictive', 'Predictive'), ('analytical', 'Analytical'), ('automation', 'Automation'), ('advisory', 'Advisory'), ('monitoring', 'Monitoring')], default='analytical', max_length=20)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('responsibilities', models.JSONField(default=list)),
                ('database_entities', models.JSONField(default=list)),
                ('model_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to='industries.industrycatalog')),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'ordering': ['industry', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyIndustryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deployment_date', models.DateField(blank=True, null=True)),
                ('custom_settings', models.JSONField(blank=True, default=dict)),
                ('compliance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('maturity_level', models.CharField(choices=[('initial', 'Initial'), ('developing', 'Developing'), ('defined', 'Defined'), ('managed', 'Managed'), ('optimizing', 'Optimizing')], default='initial', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_agents', models.ManyToManyField(blank=True, related_name='company_profiles', to='industries.aiagentregistry')),
                ('activated_controls', models.ManyToManyField(blank=True, related_name='company_profiles', to='industries.industrycontrol')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_profiles', to='core.company')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='industries.industrycatalog')),
            ],
            options={
                'verbose_name': 'Company Industry Profile',
                'verbose_name_plural': 'Company Industry Profiles',
                'unique_together': {('company', 'industry')},
            },
        ),
    ]
