# Generated by Django 4.2.30 on 2026-07-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(choices=[('SOC2_TYPE1', 'SOC 2 Type I'), ('SOC2_TYPE2', 'SOC 2 Type II'), ('ISO27001', 'ISO 27001'), ('ISO9001', 'ISO 9001'), ('ISO27701', 'ISO 27701 (Privacy)'), ('GDPR', 'GDPR Compliance'), ('PCI_DSS', 'PCI DSS'), ('HIPAA', 'HIPAA'), ('ZATCA', 'ZATCA Phase 2'), ('NCA_ECC', 'NCA Essential Controls'), ('NCA_CSCC', 'NCA Cloud Controls')], max_length=20, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('achieved', 'Achieved'), ('renewal', 'Renewal Due'), ('expired', 'Expired')], default='in_progress', max_length=15)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('auditor', models.CharField(blank=True, max_length=200)),
                ('certificate_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('last_assessment', models.DateField(blank=True, null=True)),
                ('controls_passed', models.PositiveIntegerField(default=0)),
                ('controls_total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CountryLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('country_name_ar', models.CharField(blank=True, max_length=100)),
                ('primary_tax_type', models.CharField(choices=[('vat', 'VAT'), ('gst', 'GST'), ('sales_tax', 'Sales Tax'), ('none', 'None')], default='vat', max_length=20)),
                ('standard_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_registration_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Annual revenue threshold for mandatory registration', max_digits=18, null=True)),
                ('e_invoicing_required', models.BooleanField(default=False)),
                ('e_invoicing_standard', models.CharField(blank=True, help_text='e.g. ZATCA, MyInvois, FatturaPA', max_length=50)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('accounting_standard', models.CharField(choices=[('IFRS', 'IFRS'), ('GAAP', 'US GAAP'), ('LOCAL', 'Local GAAP')], default='IFRS', max_length=20)),
                ('requires_chart_of_accounts', models.BooleanField(default=False, help_text='Government-mandated COA format')),
                ('official_coa_url', models.URLField(blank=True)),
                ('social_insurance_employer_pct', models.DecimalField(decimal_places=2, default=0, help_text='Employer social insurance / pension contribution %', max_digits=5)),
                ('social_insurance_employee_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payroll_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('regulatory_body', models.CharField(blank=True, max_length=200)),
                ('key_regulations', models.JSONField(default=list, help_text='[{"name":"VAT Law","url":"..."}]')),
                ('localization_notes', models.TextField(blank=True)),
                ('supported', models.BooleanField(default=True)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Country Localization',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('implementation', 'Implementation'), ('consulting', 'Consulting'), ('isv', 'ISV / Developer'), ('reseller', 'Reseller'), ('training', 'Training')], max_length=20)),
                ('tier', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('registered', 'Registered')], default='registered', max_length=15)),
                ('country', models.CharField(max_length=2)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('specializations', models.JSONField(default=list, help_text='["manufacturing","hr","vat"]')),
                ('certifications', models.JSONField(default=list)),
                ('active_deployments', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('pricing_model', models.CharField(choices=[('free', 'Free'), ('freemium', 'Freemium'), ('subscription', 'Subscription'), ('one_time', 'One-time')], default='free', max_length=15)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installs', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('screenshots', models.JSONField(default=list)),
                ('verified', models.BooleanField(default=False, help_text='Security-reviewed by Nexus team')),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.partner')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('verified', 'Verified')], default='not_started', max_length=15)),
                ('evidence_path', models.CharField(blank=True, help_text='URL or path to evidence artifact', max_length=500)),
                ('automated', models.BooleanField(default=False, help_text='Can evidence be auto-collected?')),
                ('automation_query', models.TextField(blank=True, help_text='Django ORM path or audit event type')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='market.certificationrecord')),
            ],
        ),
    ]
