# Generated by Django 4.2.30 on 2026-07-07 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('trusted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('protocol', models.CharField(choices=[('oidc', 'OpenID Connect / OAuth2'), ('saml', 'SAML 2.0'), ('ldap', 'LDAP / Active Directory')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('issuer', models.URLField(blank=True, help_text='OIDC issuer / discovery base')),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('scopes', models.CharField(default='openid email profile', max_length=255)),
                ('entity_id', models.CharField(blank=True, max_length=255)),
                ('sso_url', models.URLField(blank=True)),
                ('x509_cert', models.TextField(blank=True)),
                ('ldap_server', models.CharField(blank=True, help_text='ldaps://dc.example.com', max_length=255)),
                ('ldap_bind_dn', models.CharField(blank=True, max_length=255)),
                ('ldap_bind_password', models.CharField(blank=True, max_length=255)),
                ('ldap_user_search', models.CharField(blank=True, help_text='e.g. OU=Users,DC=example,DC=com', max_length=255)),
                ('jit_provisioning', models.BooleanField(default=True, help_text='Create users on first SSO login')),
                ('default_groups', models.JSONField(blank=True, default=list)),
                ('attribute_map', models.JSONField(blank=True, default=dict, help_text='{"email": "mail", "first_name": "givenName"}')),
            ],
        ),
        migrations.CreateModel(
            name='RoleMiningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('suggestions', models.JSONField(default=list)),
                ('users_analyzed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivilegedSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_requested', models.CharField(help_text='e.g. billing_admin, db_operator', max_length=100)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='requested', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_duration_minutes', models.PositiveIntegerField(default=60)),
                ('actions_log', models.JSONField(blank=True, default=list)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pam_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privileged_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=2)),
                ('hour_of_day', models.PositiveSmallIntegerField()),
                ('succeeded', models.BooleanField(default=True)),
                ('trust_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.devicefingerprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_contexts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
