# Generated by Django 4.2.30 on 2026-07-07 01:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sagainstance_projection_outboxevent_multiregionsync_and_more'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_requested', models.CharField(max_length=100)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_duration_hours', models.PositiveIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_elevations', to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevation_requests', to='core.user')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
