# Generated by Django 4.2.30 on 2026-07-06 08:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('customer_type', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual')], default='Company', max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Saudi Arabia', max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('payment_terms', models.CharField(blank=True, choices=[('Net 15', 'Net 15'), ('Net 30', 'Net 30'), ('Net 60', 'Net 60'), ('Due on Receipt', 'Due on Receipt'), ('Advance', 'Advance')], max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blacklisted', 'Blacklisted')], default='Active', max_length=50)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(max_length=100, unique=True)),
                ('transaction_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('payment_terms', models.CharField(blank=True, choices=[('Net 15', 'Net 15'), ('Net 30', 'Net 30'), ('Net 60', 'Net 60'), ('Due on Receipt', 'Due on Receipt'), ('Advance', 'Advance')], max_length=50)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('incoterm', models.CharField(blank=True, choices=[('EXW', 'EXW'), ('FOB', 'FOB'), ('CIF', 'CIF'), ('DDP', 'DDP'), ('DAP', 'DAP')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='selling.customer')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_handled', to='hr.employee')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTaxCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='VAT', max_length=255)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_charges', to='selling.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Bank Transfer', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='selling.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('delivered_qty', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='selling.salesorder')),
            ],
        ),
    ]
