# Generated by Django 4.2.30 on 2026-07-06 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('avatar', models.URLField(blank=True, verbose_name='Avatar')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA Enabled')),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last IP')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('groups', models.ManyToManyField(blank=True, related_name='tenant_users', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tenant Name')),
                ('slug', models.SlugField(max_length=63, unique=True, verbose_name='Slug')),
                ('schema_name', models.CharField(max_length=63, unique=True, verbose_name='Schema Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('cancelled', 'Cancelled')], default='trial', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='Paid Until')),
                ('on_trial', models.BooleanField(default=True, verbose_name='On Trial')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name='Trial End Date')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='Max Users')),
                ('max_storage_mb', models.PositiveIntegerField(default=100, verbose_name='Max Storage (MB)')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Company Name')),
                ('company_logo', models.URLField(blank=True, verbose_name='Company Logo')),
                ('favicon', models.URLField(blank=True, verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Primary Color')),
                ('features_enabled', models.JSONField(blank=True, default=dict, verbose_name='Enabled Features')),
                ('require_2fa', models.BooleanField(default=False, verbose_name='Require 2FA')),
                ('password_policy', models.JSONField(blank=True, default=dict, verbose_name='Password Policy')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30, verbose_name='Session Timeout')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20, verbose_name='Role')),
                ('permissions', models.JSONField(blank=True, default=dict, verbose_name='Permissions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tenant Membership',
                'verbose_name_plural': 'Tenant Memberships',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=253, unique=True, verbose_name='Domain')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary')),
                ('domain_type', models.CharField(choices=[('subdomain', 'Subdomain'), ('custom', 'Custom Domain')], default='subdomain', max_length=20, verbose_name='Domain Type')),
                ('ssl_enabled', models.BooleanField(default=False, verbose_name='SSL Enabled')),
                ('ssl_cert_path', models.CharField(blank=True, max_length=500, verbose_name='SSL Certificate Path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='tenants',
            field=models.ManyToManyField(blank=True, related_name='users', through='tenants.TenantMembership', to='tenants.tenant', verbose_name='Tenants'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='tenant_users', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
