# Generated by Django 4.2.30 on 2026-07-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_plan'),
    ]

    operations = [
        migrations.RemoveField(model_name='tenantmembership', name='invited_by'),
        migrations.AddField(model_name='tenantmembership', name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to='tenants.tenantuser', verbose_name='Invited By'),
        ),
        migrations.RemoveField(model_name='tenantmembership', name='user'),
        migrations.AddField(model_name='tenantmembership', name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenantuser', verbose_name='User'),
        ),
    ]
