# Generated by Django 4.2.30 on 2026-07-07 00:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('automated_check', models.CharField(blank=True, help_text='dotted path to a callable(company)->bool for auto-evidence', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ControlAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('partial', 'Partial'), ('not_assessed', 'Not Assessed')], default='not_assessed', max_length=15)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('automated', models.BooleanField(default=False)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='compliance.compliancecontrol')),
            ],
        ),
        migrations.AddField(
            model_name='compliancecontrol',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='compliance.complianceframework'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancecontrol',
            unique_together={('framework', 'control_id')},
        ),
    ]
