# Generated by Django 4.2.30 on 2026-07-07 01:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_sagainstance_projection_outboxevent_multiregionsync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('exempt', 'Exempt'), ('under_review', 'Under Review')], default='not_started', max_length=20)),
                ('compliance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_assessment_date', models.DateField(blank=True, null=True)),
                ('next_assessment_date', models.DateField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('action_plan', models.TextField(blank=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='core.company')),
            ],
            options={
                'verbose_name': 'Company Compliance',
                'verbose_name_plural': 'Company Compliance Records',
            },
        ),
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('framework_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('it_security', 'IT Security'), ('environmental', 'Environmental'), ('general', 'General')], default='general', max_length=100)),
                ('description', models.TextField()),
                ('version', models.CharField(blank=True, max_length=50)),
                ('issuing_body', models.CharField(blank=True, max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('review_cycle_months', models.PositiveIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compliance Framework',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('effective_date', models.DateField()),
                ('impact_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('action_required', models.BooleanField(default=False)),
                ('action_description', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='compliance.complianceframework')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('verification_method', models.TextField(blank=True)),
                ('documentation_required', models.BooleanField(default=True)),
                ('review_frequency_days', models.PositiveIntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='compliance.complianceframework')),
            ],
            options={
                'ordering': ['framework', 'requirement_id'],
                'unique_together': {('framework', 'requirement_id')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('partial', 'Partial'), ('na', 'N/A')], default='na', max_length=20)),
                ('evidence', models.TextField(blank=True)),
                ('evidence_files', models.JSONField(blank=True, default=list)),
                ('audit_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('remediation_required', models.BooleanField(default=False)),
                ('remediation_deadline', models.DateField(blank=True, null=True)),
                ('remediation_status', models.CharField(choices=[('none', 'None'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='none', max_length=20)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('company_compliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='compliance.companycompliance')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='compliance.compliancerequirement')),
            ],
            options={
                'ordering': ['-audit_date'],
            },
        ),
        migrations.AddField(
            model_name='companycompliance',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_records', to='compliance.complianceframework'),
        ),
        migrations.AlterUniqueTogether(
            name='companycompliance',
            unique_together={('company', 'framework')},
        ),
    ]
